default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", nil) %>
  username: <%= ENV.fetch("DATABASE_USERNAME", nil) %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", nil) %>

development:
  <<: *default
  database: github_analyzer_development

test:
  <<: *default
  database: github_analyzer_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
